import Head from 'next/head'
import Image from 'next/image'
import {
  StyledContainer,
  StyledMain,
  StyledFooter,
  StyledSpanLogo,
  StyledTitle,
  StyledCode,
  StyledDescription,
  StyledCardAnchor,
  StyledGrid,
} from './styles'

export const Home: React.FC<unknown> = () => {
  return (
    <StyledContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>
        <StyledTitle>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </StyledTitle>

        <StyledDescription>
          Get started by editing <StyledCode>pages/index.tsx</StyledCode>
        </StyledDescription>

        <StyledGrid>
          <StyledCardAnchor href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </StyledCardAnchor>

          <StyledCardAnchor href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </StyledCardAnchor>

          <StyledCardAnchor href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </StyledCardAnchor>

          <StyledCardAnchor href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </StyledCardAnchor>
        </StyledGrid>
      </StyledMain>

      <StyledFooter>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <StyledSpanLogo>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </StyledSpanLogo>
        </a>
      </StyledFooter>
    </StyledContainer>
  )
}
